[wokwi]
version = 1
firmware = 'C:\Users\profb\OneDrive - Etec Centro Paula Souza\Projetos\ESP32\Display LCD_I2C\Leitura Analógica\Analog_Read_I2C\.pio\build\esp32dev'
elf = 'C:\Users\profb\OneDrive - Etec Centro Paula Souza\Projetos\ESP32\Display LCD_I2C\Leitura Analógica\Analog_Read_I2C\.pio\build\esp32dev'
